name: WeaponsAddon
version: '${project.version}'
main: com.Chagui68.weaponsaddon.LegacyWeaponsAddon
api-version: '26.2'
depend: [Slimefun]
loadbefore: [Networks]
author: Chagui68
description: Military Arsenal for Slimefun Legacy on Paper/Purpur 26.2+

commands:
  weapons:
    description: Main command for Military Arsenal
    usage: /weapons <delete|reload> <args>
    permission: militaryarsenal.admin
    permission-message: You don't have permission to use this command!

permissions:
  militaryarsenal.admin:
    description: Access to Military Arsenal admin commands
    default: op
